
=head1 NAME

Finance::Shares::CGI - support for Finance::Shares cgi interface scripts

=head1 SYNOPSIS

=head2 The perl module

    use Finance::Shares::CGI;

    my $cgi = new Finance::Shares::CGI;
    my $db  = $cgi->get_records();

    $cgi->print_header($title, $text, $script, $style);
    $cgi->print_form_start($url, $code, $centered);
    $cgi->print_form_end();
    $cgi->print_footer($text);

    $cgi->show_params();
    $cgi->show_hash($hashref);
    $cgi->show_records();

=head2 Administration scripts

    init.pl
    fetch.pl
    list.pl
    drop.pl

=head2 Main processing scripts

    chart.pl
    interface.pl
    menu.pl
    shares.pl
    prefs.pl
    run.pl

=head2 Support scripts

    make_index

=head1 DESCRIPTION

The Finance::Shares::CGI module supports a number of cgi scripts which provide a web interface to the
Finance::Shares toolkit.  It requires a mysql database.  See L<Finance::Shares::Overview> or
L<Finance::Shares::MySQL> for details on setting this up.

The scripts must be manually copied to your CGI directory.  See the README file for installation details.  This
documents how the scripts work together.

=head2 Constructor

There are no parameters.  However, there are seven lines that probably need editing before use.  See the README
file for INSTALLATION details.  Use as:

    my $cgi = new Finance::Shares::CGI;

=head2 Methods

=head3 login()

Connects to the database.  Used by B<get_records>.

=head3 get_records()

This requires the CGI parameter 'u' to be set to a user name.  It will automatically register any name it does not
recognize.  The user settings are fetched and available for use.  Use as:

    use Finance::Shares::CGI;
    use CGI ':standard';

    my $cgi = new Finance::Shares::CGI;
    param('u', 'myname');
    $cgi->get_records();
    
=head3 change_user()

Call this to store any changes to the user data.

=head3 print_header( [title [, text [, script [, style]]]] )

Issue the CGI text needed to set up a standardized page.  The C<title> becomes a heading as well as the HTML page
title.  If C<text> is present it is output and subsequent text will be part of a table.  C<script> and C<style> would typically
be javascript code and the name of a CSS stylesheet.  The default is no script and F<styles.css>.  Use as:

    $cgi->print_header('My Title', $html);

=head3 print_form_start( [url [, code [, centered]]] )

Declare the start of a form after B<print_header>.  C<url> is the form action, C<code> is 'onsubmit' code and
C<centered> is a layout flag.  Use as:

    $cgi->print_form_start();

=head3 print_form_end()

Mark the end of a form declared with B<print_form_start>.

=head3 print_footer( [text] )

Mark the end of the page begun with B<print_header>.

=head3 show_error( message )

Output an error page and exit.  Use as:

    $cgi->show_error( 'No user' );

=head2 Support methods

=head3 show_hash( hashref )

Return a string comprising key=value pairs for the top level entries only.  Use as:

    print $cgi->show_hash( $h );

=head3 show_records( [table] )

Print out the objects key/value pairs within table html if C<table> is true.

head2 Administration scripts

Choose 'Admin' from the 'User levels' Preference menu.  An additional menu then gives access to these scripts.

=over 4

=item init.pl

Builds the mysql database and maintains the user interface support tables.
Mysql must have a user, password and database to match those set in Finance::Shares::CGI.pm.  Documentation is
available using

    $ perldoc init.pl

Note that C<tables> or C<users> options destroy user data.

This script may be invoked directly from a browser, provided that '?initialize=1' is appended.  It will then
initialize the database ready for the other CGI scripts.

=item fetch.pl

Fetches stock quotes into the mysql database.  Quotes are fetched when a chart or model is run, anyway.  Remember
the command line scripts F<fs_fetch> and F<fs_fetch_csv> can be found in the Finance::Shares package.

=item list.pl

Lists the mysql table names against the DBIx::Namespace user names.  Remember F<fs_list_tables> in
Finance::Shares.
    
=item drop.pl

Small changes to the tables can be made from the mysql prompt.  DON'T just delete tables, though, as
this destroys the index integrity.  It only deletes one user-name at a time. Use list.pl to identify
them.  This does the same job as F<fs_drop_table> from the Finance::Shares package.

=back

=head2 Main processing scripts

These are the scripts which serve the site's main purpose, to make the hundreds of options more manageable.

=over 4

=item shares.pl

Top of site, this generates the frameset holding menu and content frames.

=item menu.pl

Generates the menu according to session browser settings

=item interface.pl

The main script, driven by params 't' (table name), 'a' (arguments) and 'name' (of user settings) which determine
the layout described in the init.pl tables.

=item prefs.pl

Help and option levels for user.  There are three user levels, mostly done, but the three help levels are all the
same at present.

=item chart.pl

Generates PostScript chart from 'Draw chart' settings.

=item run.pl

Runs a model and returns a chart with the results.

=back

=head2 Support scripts

=over 4

=item make_index

Constructs the file F<index.html> using the same settings as all the cgi scripts.

=back

=cut


